- name: "Read env variables"
  include_vars:
    file: "vars/{{ PROJECT }}_{{ ENV }}.yml"


# Basic provisioning example
- ec2:
     region: "{{ region }}"   
     key_name: "{{ key_name }}"
     instance_type: "{{ instance_type }}"
     image: "{{ image }}"
     wait: yes
     group: "{{ group }}"
     vpc_subnet_id: "{{ vpc_subnet_id}}"
     assign_public_ip: yes
